# Eureka Server Port (default)
server:
  port: 8761

# Eureka Server\uB294 \uC790\uAE30 \uC790\uC2E0\uC774 Server
# Server\uC5D0 \uB4F1\uB85D\uD558\uC9C0 \uC54A\uAE30 \uC704\uD574 register-with-eureka: false
# \uB2E4\uB978 \uC11C\uBE44\uC2A4\uB97C \uC8FC\uAE30\uC801\uC73C\uB85C \uAC31\uC2E0\uD574\uC11C \uC778\uC9C0\uD558\uAE30 \uC704\uD55C \uC124\uC815\uB3C4 fetch-registry: false
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka